version: '3'
services:
  

  server:
    # find the Dockerfile in ./backend to build the image
    build: ../nanogram
    ports:
      - 3000:3000

  db:
    # find the Dockerfile in ./db to build the image
    build: ./db
